---
- hosts: all
  become: yes
  vars:
    server_ip: 158.160.65.62
  tasks:
  - name: test vars
    # debug: "msg='Debug variable testing: {{ client }}'"
    debug: "msg='Настройки клиента {{ ansible_ssh_host }} для сервера {{ server_ip }}'"